services:
  frontend:
    build:
      context: .
      target: development
    env_file:
      - .env
    ports:
      - 3001:3001
    stdin_open: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express

networks:
  react-express:

